In [35]:
import numpy as np
from pyml.tensor import tensor

tensor_zeros = tensor.zeros(3, 3, dtype="int8") 
print("Tensor filled with zeros:")
print(tensor_zeros)
print(tensor_zeros.dtype)

Tensor filled with zeros:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
int8


In [37]:
a = tensor([1, 2, 3], dtype='int32')
b = tensor([1, 2, 3], dtype='float32')
result = a * b
print(result.dtype, 'int32')

TypeError: unsupported operand type(s) for *: 'tensor' and 'tensor'